### PR TITLE
Add SimilarityModel3D

### PR DESCRIPTION
**Pull request by bogovicj**
Added 3d similarity model.

Based on:
https://github.com/bigdataviewer/SPIM_Registration/blob/master/src/main/java/mpicbg/pointdescriptor/model/TranslationInvariantSimilarityModel3D.java

### CODE REVIEW

**Comment by axtimwalde** [comment]
Thanks!  Could you also please implement fit(double[][], double[][], double[]) and fit(float[][], float[][], float[])?  AbstractAffineModel has default implementations that are pretty wasteful
https://github.com/axtimwalde/mpicbg/blob/master/mpicbg/src/main/java/mpicbg/models/AbstractModel.java#L575
It basically means copying some code, may be externalize some of the operations in to private static methods...

**Comment by bogovicj** [comment]
Makes sense, will do.

**Comment by axtimwalde** [comment]
Thanks!  Why didn't we merge this in summer?

**Comment by bogovicj** [comment]
Yikes, guess we both just forgot

**Pull request merged**
