### PR TITLE
remove logging to improve performance

### PR DESCRIPTION
**Pull request by CellKai**
commenting the IJ.log improves performance approximately 12-fold.
This is especially relevant when using BigStitcher / Multiviewreconstruction on a datasest with many tiles and time points.

- I tested this using a small h5/xml dataset containing 4 tiles, 3 time points, 1 channel, 1 illumination, 1 angle (total size 1.2GB)
- Using Bigstitcher with advanced grouping, comparing both tiles AND time points results in 40 comparisons.
- using latest vanilla Fiji + Bigstitcher (BigStitcher v1.1.5 v, multiview-reconstruction v1.2.9, mpicbg v1.4.2 ):
- executing the step "optimize globally and apply shifts" with two round optimization method selected:
- BEFORE: 25 seconds
- AFTER: 2 seconds

@StephanPreibisch  @tpietzsch

### CODE REVIEW

**Comment by tpietzsch** [comment]
In `IJ.log( i + ": " + observer.mean + " " + observer.max );`, do you know how much of the time is spent for the concatenation of the `String` argument? I would guess, almost all of the overhead is the actual `IJ.log`, but I don't know. If so, maybe it would be worthwhile to consider moving mpicbg to a logging framework (where the user can turn it off), instead of just flat out removing the possibility.

**Comment by CellKai** [comment]
Hi, not sure if this question was directed to me :sweat_smile: . I don't know how much time is spent for the string concatenation, or how much is spent to get the values for observer.mean and observer.max, respectively. I suppose in any case it would make sense to move to a logging framework and have this printout optional for debugging only.

**Comment by StephanPreibisch** [comment]
I’m almost convinced @trautmane would really enjoy doing that 😊 How do you feel about an extra (log4j) dependency @axtimwalde ?

**Comment by axtimwalde** [comment]
Fine.

**Pull request merged**
