### PR TITLE
replaced IJ.log by System.out.println for reporting each iteration status

### PR DESCRIPTION
**Pull request by StephanPreibisch**
The ImageJ log is otherwise pretty confusing ...

### CODE REVIEW

**Comment by axtimwalde** [comment]
Will not merge this because logging is useful for me and System.out is not a useful log.  Adding a boolean flag for logging to the method and preserving the current method footprint with default==true would be ok.

**Comment by ctrueden** [comment]
Since this PR is not going to merge, how about closing it?

**Comment by axtimwalde** [comment]
Closing for now...

**Comment by StephanPreibisch** [comment]
Ok, it is not really relevant for me ... it was a rather visual thing. Maybe I will go after this when there is more time :)

**Pull request closed without merging**
